apiVersion: v1
kind: Service
metadata:
  name: kube-service
spec:
  selector:
    app: kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

  # type: NodePort      // locally
  # type: LoadBalancer    // on cloud providers, like aws